In [ ]:
import numpy as np

In [ ]:
matrix=np.ones((5,5))
matrix[1:-1,1:-1]=0
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
np.random.seed(42)
random_data=np.random.randn(100,3)
mean=random_data.mean(axis=0)
std=random_data.std(axis=0)
normalize=(random_data-mean)/std
print(normalize.mean(axis=0))
print(normalize.std(axis=0))

[-2.60902411e-17  1.55431223e-17 -8.88178420e-18]
[1. 1. 1.]
